spring:
  application:
    name: user-role-auth-service
  datasource:
    url: jdbc:postgresql://postgresql-svc:5432/postgres
    #url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging:
  level:
    sql: debug
server:
  port: 8080
  error:
    include-message: always