apiVersion: apps/v1

kind: Deployment

metadata:
  name: httpd-frontend
  labels:
    app: httpd-frontend-app
  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd-frontend-app
      type: front-end

  template:
    metadata:
      name: httpd-frontend
      labels:
        app: httpd-frontend-app
        type: front-end
    spec:
      containers:
        - name: httpd
          image: httpd:2.4-alpine