apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_DB: cG9zdGdyZXM=
  REPLICATION_USER: cmVwbGljYXRpb251c2Vy
  REPLICATION_PASSWORD: cmVwbGljYXRpb25QYXNzd29yZA==
