apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  securityContext:
    runAsUser: 1001
  containers:
    -  image: ubuntu
       name: web
       command: ["sleep", "5000"]
       securityContext:
         runAsUser: 1002
         capabilities:
           add:
             - "SYS_TIME"

    -  image: ubuntu
       name: sidecar
       command: ["sleep", "5000"]

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-02-05T22:07:13Z"
  name: ubuntu-sleeper
  namespace: default
  resourceVersion: "768"
  uid: ec2c4ffe-99c9-4cca-b57b-00e716fd6c97
spec:
  containers:
    - command:
        - sleep
        - "4800"
      image: ubuntu
      imagePullPolicy: Always
      name: ubuntu
      securityContext:
        capabilities:
          add:
            - "SYS_TIME"