apiVersion: v1

kind: Pod

metadata:
  name: myapp-pod
  labels:
    name: myapp
   
spec:
  containers:
  - name: nginx-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8081

---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: myapp
spec:
  containers:
    - name: redis-pod
      image: redis