apiVersion: v1
kind: pod
metadata:
  name: webapp-color
  labels:
    name: webapp-color
spec:
  containers:
    - name: webapp-color
      image: webapp-color
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: app-config