apiVersion: v1
kind: Pod
metadata:
  name: test-app-secret
  labels:
    app: test-app-secret
spec:
  containers:
    - name: test-app-secret
      image: test_image-secret
      imagePullPolicy: IfNotPresent
      envFrom:
        - secretRef:
            name: app-secret
      env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_PASSWORD

  restartPolicy: OnFailure

